apiVersion: v1 
kind: PersistentVolumeClaim 
metadata: 
   name: mysql-pvc 
spec: 
   storageClassName: mysql-sc 
   accessModes: 
     - ReadWriteOnce 
   resources: 
     requests: 
       storage: 2Gi