kind: PersistentVolume 
apiVersion: v1 
metadata: 
   name: mysql-pv 
spec: 
   storageClassName: mysql-sc
   persistentVolumeReclaimPolicy: Retain 
   capacity: 
      storage: 2Gi 
   accessModes: 
      - ReadWriteOnce 
   hostPath: 
      path: /var/output