apiVersion: v1
kind: Service
metadata:
  name: notepad-nodeport
spec:
  type: NodePort
  selector:
    app: notepad
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000